#!/usr/bin/env bash
# Rickthon - UserBot
# Copyright (C) 2021-2022 Rickthon 
#
# This file is a part of < https://github.com/rick1128/userbot/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/rick1128/userbot
    cd Ultroid
fi
bash resources/startup/termux.sh
